name       : python-asttokens
version    : 2.0.5
release    : 4
source     :
    - https://files.pythonhosted.org/packages/aa/51/59965dead3960a97358f289c7c11ebc1f6c5d28710fab5d421000fe60353/asttokens-2.0.5.tar.gz : 9a54c114f02c7a9480d56550932546a3f1fe71d8a02f1bc7ccd0ee3ee35cf4d5
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - pkgconfig(python3)
    - python-astroid
    - python-pytest
    - python-setuptools-scm
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    Fine on 3.9 fails on 3.7
#    %python3_test
