name       : python-asttokens
version    : 2.1.0
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/a/asttokens/asttokens-2.1.0.tar.gz : 4aa76401a151c8cc572d906aad7aea2a841780834a19d780f4321c0fe1b54635
homepage   : https://github.com/gristlabs/asttokens
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - python-astroid # check
    - python-pytest  # check
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Issues with latest python-astroid.
    # https://github.com/gristlabs/asttokens/issues/79
    %python3_test pytest3 -v -k 'not test_astroid'
