name       : python-asttokens
version    : 2.4.0
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/a/asttokens/asttokens-2.4.0.tar.gz : 2e0171b991b2c959acc6c49318049236844a5da1d65ba2672c4880c1c894834e
homepage   : https://github.com/gristlabs/asttokens
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - python-astroid # check
    - python-pytest  # check
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
