name       : python-asttokens
version    : 1.1.13
release    : 1
source     :
    - https://files.pythonhosted.org/packages/99/03/2ac29b8b0f0fc51fdc19958e7bd85413c5c0090a5ee169f37e581b9e4374/asttokens-1.1.13.tar.gz : 55c00658f9e0fa7e031529c719e8bb2cdbad0ad973aaff08faf6bfdaa96ca4ed
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
