name       : python-asttokens
version    : 2.0.8
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/a/asttokens/asttokens-2.0.8.tar.gz : c61e16246ecfb2cde2958406b4c8ebc043c9e6d73aaa83c941673b35e5d3a76b
homepage   : https://github.com/gristlabs/asttokens
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - python-astroid # check
    - python-pytest  # check
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Issues with latest python-astroid.
    # https://github.com/gristlabs/asttokens/issues/79
    %python3_test pytest3 -v -k 'not test_astroid'
