name       : python-asttokens
version    : 2.0.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/d2/0c/3352d16e74256f0fc371640eed1106d21272e39af98fbdd0998711b5e1bc/asttokens-2.0.2.tar.gz : 61529725926378f2d0497d970d243cab68c39d6374dfc0bd7976e29296fb7843
license    : Apache-2.0
component  : programming.python
summary    : Annotate Python AST trees with source text and token information
description: |
    The asttokens module annotates Python abstract syntax trees (ASTs) with the positions of tokens and text in the source code that generated them.
builddeps  :
    - pkgconfig(python3)
    - python-astroid
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
